package com.ubertimetracker.data.model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime

/**
 * Represents a single work session
 */
@Entity(tableName = "sessions")
@Parcelize
data class Session(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val date: LocalDate,
    val startTime1: LocalTime?,
    val stopTime1: LocalTime?,
    val pauseDuration: Long = 0, // in minutes
    val totalPauseDuration: Long = 0, // Gesamtpause in minutes
    val startTime2: LocalTime?,
    val stopTime2: LocalTime?,
    val totalHours: Double = 0.0, // Gesamtstunden
    val isAutoGenerated: Boolean = false,
    val hasConflict: Boolean = false,
    val conflictMessage: String? = null,
    val syncStatus: SyncStatus = SyncStatus.PENDING,
    val createdAt: LocalDateTime = LocalDateTime.now(),
    val updatedAt: LocalDateTime = LocalDateTime.now()
) : Parcelable

/**
 * Sync status enum
 */
enum class SyncStatus {
    PENDING,
    SYNCED,
    FAILED,
    OFFLINE
}

/**
 * Represents a pause during a session
 */
@Entity(tableName = "pauses")
@Parcelize
data class Pause(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val sessionId: Long,
    val startTime: LocalTime,
    val endTime: LocalTime?,
    val durationMinutes: Long = 0
) : Parcelable

/**
 * Timer state for the current session
 */
@Parcelize
data class TimerState(
    val isRunning: Boolean = false,
    val isPaused: Boolean = false,
    val startTimeMillis: Long = 0,
    val pausedTimeMillis: Long = 0,
    val totalPausedDuration: Long = 0,
    val elapsedTime: Long = 0,
    val currentSessionId: Long? = null
) : Parcelable

/**
 * Debug log entry for the Live Debug Inspector
 */
data class DebugLogEntry(
    val id: Long = System.currentTimeMillis(),
    val timestamp: LocalDateTime = LocalDateTime.now(),
    val type: LogType,
    val message: String,
    val details: String? = null
)

enum class LogType {
    SYSTEM,
    OCR,
    LANGUAGE,
    ANALYSIS,
    ACTION,
    SYNC,
    ERROR,
    WARNING
}

/**
 * Detected language from OCR
 */
data class DetectedLanguage(
    val code: String,
    val name: String,
    val confidence: Float = 1.0f
)

/**
 * Uber app status detected via accessibility
 */
enum class UberAppStatus {
    ONLINE,
    OFFLINE,
    BUSY,
    UNKNOWN
}

/**
 * App settings
 */
@Entity(tableName = "settings")
data class AppSettings(
    @PrimaryKey
    val id: Int = 1,
    val isDarkMode: Boolean? = null, // null = system default
    val autoSyncEnabled: Boolean = true,
    val selectedLanguage: String = "EN",
    val offlineCacheEnabled: Boolean = true,
    val cloudSyncEnabled: Boolean = true,
    val notificationsEnabled: Boolean = true
)

/**
 * Weekly summary for analytics
 */
data class WeeklySummary(
    val weekNumber: Int,
    val year: Int,
    val totalHours: Double,
    val daysWorked: Int,
    val sessions: List<Session>
)

/**
 * Monthly summary for analytics
 */
data class MonthlySummary(
    val month: Int,
    val year: Int,
    val totalHours: Double,
    val weeklySummaries: List<WeeklySummary>,
    val daysWorked: Int
)

/**
 * Export configuration
 */
data class ExportConfig(
    val format: ExportFormat,
    val includeWeeklyTotals: Boolean = true,
    val includeMonthlyTotal: Boolean = true,
    val month: Int,
    val year: Int,
    val language: String = "DE"
)

enum class ExportFormat {
    EXCEL,
    WORD,
    PDF
}

/**
 * Timesheet row for display
 */
data class TimesheetRow(
    val date: LocalDate,
    val sessions: List<Session>,
    val pauses: List<Pause> = emptyList(),
    val dayName: String,
    val isWeekend: Boolean,
    val isHoliday: Boolean = false,
    val weekNumber: Int
)

/**
 * Timesheet entry for export and display
 */
data class TimesheetEntry(
    val date: LocalDate,
    val segments: List<WorkSegment> = emptyList(),
    val totalDailyHours: String? = null,
    val hasConflict: Boolean = false,
    val weekNumber: Int = 0
)

sealed class WorkSegment {
    data class Work(
        val startTime: String,
        val endTime: String?
    ) : WorkSegment()
    
    data class Pause(
        val startTime: String,
        val endTime: String?,
        val duration: String?
    ) : WorkSegment()
}
